package com.mycompany.bustickets.entity;
// Generated 2017-06-20 15:53:46 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tickets generated by hbm2java
 */
@Entity
@Table(name="tickets"
    ,catalog="busticket"
)
public class Tickets  implements java.io.Serializable {


     private Integer idTicket;
     private Locations locationsByFrom;
     private Locations locationsByTo;
     private Trips trips;
     private Users users;
     private int numOfNormal;
     private int numOfDiscount;
     private String name;
     private String surname;
     private String phone;
     private String email;

    public Tickets() {
    }

	
    public Tickets(Locations locationsByFrom, Locations locationsByTo, Trips trips, int numOfNormal, int numOfDiscount) {
        this.locationsByFrom = locationsByFrom;
        this.locationsByTo = locationsByTo;
        this.trips = trips;
        this.numOfNormal = numOfNormal;
        this.numOfDiscount = numOfDiscount;
    }
    public Tickets(Locations locationsByFrom, Locations locationsByTo, Trips trips, Users users, int numOfNormal, int numOfDiscount, String name, String surname, String phone, String email) {
       this.locationsByFrom = locationsByFrom;
       this.locationsByTo = locationsByTo;
       this.trips = trips;
       this.users = users;
       this.numOfNormal = numOfNormal;
       this.numOfDiscount = numOfDiscount;
       this.name = name;
       this.surname = surname;
       this.phone = phone;
       this.email = email;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idTicket", unique=true, nullable=false)
    public Integer getIdTicket() {
        return this.idTicket;
    }
    
    public void setIdTicket(Integer idTicket) {
        this.idTicket = idTicket;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`from`", nullable=false)
    public Locations getLocationsByFrom() {
        return this.locationsByFrom;
    }
    
    public void setLocationsByFrom(Locations locationsByFrom) {
        this.locationsByFrom = locationsByFrom;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`to`", nullable=false)
    public Locations getLocationsByTo() {
        return this.locationsByTo;
    }
    
    public void setLocationsByTo(Locations locationsByTo) {
        this.locationsByTo = locationsByTo;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="idTrip", nullable=false)
    public Trips getTrips() {
        return this.trips;
    }
    
    public void setTrips(Trips trips) {
        this.trips = trips;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="idUser")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="numOfNormal", nullable=false)
    public int getNumOfNormal() {
        return this.numOfNormal;
    }
    
    public void setNumOfNormal(int numOfNormal) {
        this.numOfNormal = numOfNormal;
    }

    
    @Column(name="numOfDiscount", nullable=false)
    public int getNumOfDiscount() {
        return this.numOfDiscount;
    }
    
    public void setNumOfDiscount(int numOfDiscount) {
        this.numOfDiscount = numOfDiscount;
    }

    
    @Column(name="name", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="surname", length=50)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }

    
    @Column(name="phone", length=9)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


